devices: 
# change this to a keyboard device
- "/dev/input/event16"
# this is executed when mouseless starts
startCommand: "pkill sxhkd; setxkbmap -option; setxkbmap -layout pl -variant real-prog-dvorak; xset r rate 250 40; sxhkd -m 1 -c ~/.config/bspwm/sxhkd/sxhkdrc &"

# the default speed for mouse movement
baseMouseSpeed: 650.0
# the default speed for scrolling
baseScrollSpeed: 20.0
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when tab is held and another key pressed, activate mouse layer
    # tab: tap-hold-next tab ; toggle-layer mouse ; 500
    capslock: tap-hold capslock ; toggle-layer mouse ; 100
    # when a is held for 300ms, activate mouse layer
    # a: tap-hold a ; toggle-layer mouse ; 300
    # right alt key toggles arrows layer
    # rightalt: tap-hold-next rightalt ; toggle-layer mouse ; 900
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    # quit mouse layer
    x: layer initial
    space: layer initial
    # keep the mouse layer active
    b: layer mouse
    r: reload-config
    p: move  1  0
    j: move -1  0
    c: move  0  1
    v: move  0 -1
    r: scroll up
    l: scroll down
    leftalt: speed 4.0
    a: speed 0.3
    leftctrl: speed 0.1
    y: button left
    h: button middle
    n: button right
    # move to the top left corner
    k0: "exec xdotool mousemove 0 0"
# another layer for arrows and some other keys
- name: arrows
  passThrough: true
  bindings:
    e: up
    s: left
    d: down
    f: right
    q: esc
    w: backspace
    r: delete
    v: enter


